proxy:
    general:
        my:
            servlet_url: /MyWeb/*
            target_url: https://ozkansari.com/MyWeb

server:
    port: 8008

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false